CREATE TABLE [dbo].[DadosEstufa](
	[Id] [int] NOT NULL,
	[Id_Estufa] [int] NOT NULL,
	[Id_Temperatura] [varchar](100) NOT NULL,
	[Temperatura] [numeric](9, 2) NULL,
	[Data] [datetime] NOT NULL,
	[Tensao] [numeric](9, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[DadosEstufa]  WITH CHECK ADD  CONSTRAINT [FK_SuaTabela_Estufa] FOREIGN KEY([Id_Estufa])
REFERENCES [dbo].[Estufa] ([Id])
GO

ALTER TABLE [dbo].[DadosEstufa] CHECK CONSTRAINT [FK_SuaTabela_Estufa]
GO

CREATE UNIQUE NONCLUSTERED INDEX [UQ_DadosEstufa_Id_Temperatura] ON [dbo].[DadosEstufa]
(
	[Id_Temperatura] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
